---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ocs-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ocs-operator
    spec:
      containers:
      - command:
        - ocs-operator
        env:
        - name: OPERATOR_NAME
          value: ocs-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/openshift/ocs-operator:latest
        imagePullPolicy: Always
        name: ocs-operator
        ports:
        - containerPort: 60000
          name: metrics
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/operator-sdk-ready
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: ocs-operator
